services:
  app-service:
    build: ./services/app
    ports:
      - "4002:4002"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
  user-service:
    build: ./services/users
    ports:
      - "4001:4001"
    environment:
      MONGODB_URI: ${MONGODB_URI}
  orchestrator:
    build: ./orchestrator
    ports:
      - "80:4000"
    environment:
      Password_Redis_Labs: ${Password_Redis_Labs}
      Username_Redis_Labs: ${Username_Redis_Labs}
